### ISSUE TITLE
What does the warning mean in the Phonon spectra example

### ISSUE THREAD

**Issue by xiongyan21** [nwchemgit/nwchem#173]
When running the NWCHEM example "Diamond 2 atom fcc cell Brillouin sampling=9x9x9 M-P - Phonon spectra", the following warning appear
...

input psi filename:./diamond-dos.movecs
Warning - Orthogonalization performed, spin,zone: 1   1
        - error(before)=  0.546565E+00 (  0.345343E+01)
        - error(after)=   0.000000E+00 (  0.400000E+01)
...

I wonder what this mean and how it affects the results, and whether analytic Hessian was implemented here.

At last, it failed
...
g(w) and N(w) Used For Calculating Thermodynamic Functions
      ----------------------------------------------------------
...
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7fb8a07902da in ???
#1  0x7fb8a078f503 in ???
#2  0x7fb89f87df1f in ???
#3  0x5573f910a5b1 in util_ascii_plotter_
	at /home/hp/computation/nwchem6.8/src/util/util_ascii_plot.F:48
#4  0x5573f9045fc2 in vib_vdos_thermo_
	at /home/hp/computation/nwchem6.8/src/vib/vib_phonon.F:554
#5  0x5573f904e2c0 in vib_phonon_
	at /home/hp/computation/nwchem6.8/src/vib/vib_phonon.F:443
#6  0x5573f903ef0a in vib_vib_
	at /home/hp/computation/nwchem6.8/src/vib/vib_vib.F:226
#7  0x5573f8abf8f3 in task_freq_
	at /home/hp/computation/nwchem6.8/src/task/task_freq.F:123
#8  0x5573f8aae13a in task_
	at /home/hp/computation/nwchem6.8/src/task/task.F:406
#9  0x5573f8aa5f65 in nwchem
	at /home/hp/computation/nwchem6.8/src/nwchem.F:313
#10  0x5573f8aa65ab in main
	at /home/hp/computation/nwchem6.8/src/nwchem.F:397
Perhaps the SSD capacity is not enough or it cannot handle the data produced by the CPU threads, thus I will
reduce the threads and retry.
[3.log](https://github.com/nwchemgit/nwchem/files/4065537/3.log)

Very Best Regards!

**Comment by xiongyan21** [comment]
It also failed on Mac.
[333.log](https://github.com/nwchemgit/nwchem/files/4120328/333.log)

**Comment by xiongyan21** [comment]
When running the example serially using NWCHEM6.8 and NWCHEM7.0.0, the errors are the same 
...
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

The log files are attached
[33.log](https://github.com/nwchemgit/nwchem/files/4687959/33.log)
[3333.log](https://github.com/nwchemgit/nwchem/files/4687962/3333.log)

What is the bug here?

Very Best Regards!

**Comment by ebylaska** [comment]
I put a temporary fix for your problem.  The frozen phonon approximation doesn't seem to work for this two atom system. 
 I'll try to take a look more closely asap.

**Comment by xiongyan21** [comment]
I have retried the example using NWCHEM7.0.2, just compiled from source, but it still encountered the same mistake, although the layout in the log file is different. It seems it is caused by a file cannot be opened or cannot be written.
The log file is attached, and a parallel run is slow.
[33333.log](https://github.com/nwchemgit/nwchem/files/5658385/33333.log)
Very Best Regards!
