### ISSUE TITLE
SEGV on a particular input file

### ISSUE THREAD

**Issue by yurivict** [nwchemgit/nwchem#462]
**Describe the bug**
```
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x804a1f6db in ???
#1  0x804a1e896 in ???
#2  0x803729f6f in handle_signal
	at /disk-samsung/freebsd-src/lib/libthr/thread/thr_sig.c:303
#3  0x80372953e in thr_sighandler
	at /disk-samsung/freebsd-src/lib/libthr/thread/thr_sig.c:246
#4  0x7ffffffff192 in ???
#5  0x803dd91b1 in ???
#6  0x803badeb5 in ???
#7  0x803298434 in ???
#8  0x80329901d in ???
#9  0x802f076a9 in ???
#10  0x802e70b74 in ???
#11  0x9f454c in ???
#12  0x9e379f in ???
#13  0x7f38de in ???
#14  0x7e7ba4 in ???
#15  0x582d21 in ???
#16  0x583157 in ???
#17  0x421a14 in ???
#18  0x422db0 in ???
#19  0x41462d in ???
#20  0x40e0e1 in ???
#21  0x40c71c in ???
#22  0x40c82f in ???
Segmentation fault
```

Input: [x.nw.gz](https://github.com/nwchemgit/nwchem/files/7401815/x.nw.gz)

Log: [x.log](https://github.com/nwchemgit/nwchem/files/7401823/x.log)

**Describe settings used**
No special environment variables.
OS: FreeBSD 13

**Comment by yurivict** [comment]
This file also SEGVs.

**Comment by edoapra** [comment]
> This file also SEGVs.

This clear show that your installation is not working correctly. Does any of the QA test work?
