### ISSUE TITLE
Lucia issues 

### ISSUE THREAD

**Issue by edoapra** [nwchemgit/nwchem#563]
This a place to keep track of issues for the lucia module

**Comment by edoapra** [comment]
Undefined variable `IR` in `GASDN2`
https://github.com/nwchemgit/nwchem/commit/ac9c8d7f634e3c97f2b6dab1fcae8ea33dfac3b0

**Comment by wadejong** [comment]
@edoapra Sorry, this ended up being an input bug that only showed up in parallel as we do some analysis to maximize parallel distribution of the CI vectors. Replacing the input file by the following will resolve the issue:

title "MCSCF H2"

start h2mol

charge 0
memory  stack 200 mb heap 200 mb global 3600 mb
geometry units angstrom nocenter noautoz noautosym
  H     0.0000000    0.0000000    0.4000000
  H     0.0000000    0.0000000   -0.4000000
symmetry c1
end

basis cartesian 
H    S
     13.0100000              0.0196850
      1.9620000              0.1379770
      0.4446000              0.4781480
      0.1220000              0.5012400
H    S
      0.1220000              1.0000000
H    P
      0.7270000              1.0000000
end

scf
  singlet
  rhf
  vectors hcore output c2h4.movecs
  print "final vectors analysis"
end

task scf ignore

set lucia:nactel 2 
set lucia:ms2 0
set lucia:sym 1    
set lucia:nroot 1
set lucia:itra_route 2
set lucia:mscomb 1.0d0
set lucia:cistor 2
set lucia:icnfbat 2
set lucia:idensi 0
set lucia:ciconv 1.0d-8
set lucia:inideg 1
set lucia:inactive 0
set lucia:ngas 1
set lucia:gassh 2  
set lucia:second "REST"
set lucia:machine "CRAY"
set lucia:ncispc 2
set lucia:nirrep 1
set lucia:gsoccx 2 2 2 2
set lucia:nseqci 1 
set lucia:seq_1_1 "MCSCF,20,1"
set lucia:mxciv 5
set lucia:maxitm 20
set lucia:resdim 20
set lucia:nomofl .true.
set lucia:finorb "PS_CAN"
set lucia:nocsf .true.
set lucia:ICNFBAT 1
set lucia:IPRMCSCF 1
set lucia:ptfock .true.
set lucia:IH0_CSF 1
task lucia

**Comment by edoapra** [comment]
Could you upload the input and output files that work for a 2 processors run?
I am getting the following on a RHEL6 system
```
Bounds on accumulated occupations for space:   1
 ======================================================

         Min. occ    Max. occ
         ========    ========
   GAS 1     2           2
 Bounds on accumulated occupations for space:   2
 ======================================================

         Min. occ    Max. occ
         ========    ========
   GAS 1     2           2

 GAS   1: GAS of P-Space
 imofromto         216962957317                    1                    0

Program received signal 11 (SIGSEGV): Segmentation fault.

Backtrace for this error:

Backtrace for this error:
#0  0x00000032e7e0f2a4 in wait () from /lib64/libpthread.so.0
#1  0x00000032ea61400d in ?? () from /usr/lib64/libgfortran.so.3
#2  0x00000032ea61582e in ?? () from /usr/lib64/libgfortran.so.3
#3  0x00000032ea6146ca in ?? () from /usr/lib64/libgfortran.so.3
#4  <signal handler called>
#5  0x00000000006b3be9 in fraggas_ ()
#6  0x00000000006cb422 in optimum_gas_for_ciblocks_ ()
#7  0x000000000046e057 in lucia (rtdb=0) at lucia.F:11006
#8  0x0000000000411525 in task (rtdb=0) at task.F:354
#9  0x0000000000405fd5 in nwchem () at nwchem.F:331
#10 0x0000000000406598 in main (argc=2, argv=0x7ffc94acd656 '/scratch/edo/nwchem-l/bin/LINUX64/nwchem\000') at nwchem.F:415
#11 0x00000032e721ed20 in __libc_start_main () from /lib64/libc.so.6
#12 0x0000000000403f39 in _start ()
#0  0x00000032e7e0f2a4 in wait () from /lib64/libpthread.so.0
#1  0x00000032ea61400d in ?? () from /usr/lib64/libgfortran.so.3
#2  0x00000032ea61582e in ?? () from /usr/lib64/libgfortran.so.3
#3  0x00000032ea6146ca in ?? () from /usr/lib64/libgfortran.so.3
#4  <signal handler called>
#5  0x00000000006b3be9 in fraggas_ ()
#6  0x00000000006cb422 in optimum_gas_for_ciblocks_ ()
#7  0x000000000046e057 in lucia (rtdb=0) at lucia.F:11006
#8  0x0000000000411525 in task (rtdb=0) at task.F:354
#9  0x0000000000405fd5 in nwchem () at nwchem.F:331
#10 0x0000000000406598 in main (argc=2, argv=0x7ffd75943656 '/scratch/edo/nwchem-l/bin/LINUX64/nwchem\000') at nwchem.F:415
#11 0x00000032e721ed20 in __libc_start_main () from /lib64/libc.so.6
#12 0x0000000000403f39 in _start ()
```

**Comment by wadejong** [comment]
Do you want me to update master or do a pull request?

**Comment by edoapra** [comment]
A pull request works better. If you assign me as a reviewer, I could add (if needed) changes on top your existing ones.
