### ISSUE TITLE
SegV when USE_INTERNALBLAS=1 for version 7.2.0

### ISSUE THREAD

**Issue by edoapra** [nwchemgit/nwchem#804]
**Describe the bug**
An  segmentation violation occurs when `USE_INTERNALBLAS=1` using the 7.2.0 tarball https://github.com/nwchemgit/nwchem/releases/download/v7.2.0-release/nwchem-7.2.0-release.revision-d0d141fd-srconly.2023-03-10.tar.bz2

**Describe settings used**
```
USE_INTERNALBLAS=1
ARMCI_NETWORK=OPENIB
```

**Attach log files**
* debugging stack

```
(gdb) where
#0  0x00002ae7152b4f5d in pause () from /usr/lib64/libpthread.so.0
#1  0x0000000000ee781d in SigSegvHandler ()
#2  <signal handler called>
#3  0x0000000000fe45f0 in dcopy_ ()
#4  0x0000000000f38d9d in ycopy_ ()
#5  0x0000000000a026c4 in pstat_init (max_timers=20, nacc=1, 
    accnames=' \000\000\001\000\000\000\000\000\000\000\026\000\000\000\000\000\000\000Previous task information\000\000\000\000\000\000\000\006\000\000\000\000\000\000\000nwchem.F\000\000\000\000\000\000\000\000(/,  ', _accnames=1) at pstat_init.F:32
#6  0x000000000040a764 in nwchem () at nwchem.F:240
#7  0x000000000040b009 in main (argc=2, argv=0x7ffd534bde4e) at nwchem.F:415
```
**To Reproduce**
The default nwchem.nw input reproduces it.

Output file
```
 Scaling coordinates for geometry "geometry" by  1.889725989
 (inverse scale =  0.529177249)

 C2V symmetry detected
0:Segmentation Violation error, status=: 11
(rank:0 hostname:t84.emsl.pnl.gov pid:239162):ARMCI DASSERT fail. ../../ga-5.8.2/armci/src/common/signaltrap.c:SigSegvHandler():315 cond:0
```

Reported in the users' group   
https://groups.google.com/g/nwchem-forum/c/3MDiu3TLgaY/m/J0ZO4sw9AQAJ

**Comment by edoapra** [comment]
fixed in master and hotfix/relese-7-2-0
